# Generated by Django 4.1.2 on 2022-10-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(default=None, max_length=10000)),
                ('chat_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=300)),
                ('link', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('little_description', models.CharField(default=None, max_length=500)),
                ('main_description', models.CharField(default=None, max_length=50000)),
                ('documents', models.FileField(upload_to=None)),
                ('host', models.CharField(default=None, max_length=100)),
                ('skills', models.CharField(default=None, max_length=300)),
                ('likes', models.IntegerField(default=-1)),
                ('link', models.URLField(default=None, max_length=300)),
                ('date_of_public', models.DateTimeField(default=None)),
                ('id_of_command_developments', models.IntegerField(default=-1)),
                ('applications', models.CharField(default=None, max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='ouruser',
            name='age',
        ),
        migrations.AddField(
            model_name='ouruser',
            name='bornAge',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='busyness',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='citizenship',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='description',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='education',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='experience',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='fio',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='image',
            field=models.ImageField(default=None, upload_to=None),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='inn',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='isActivated',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='isAuthor',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='isCompany',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='isForm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='isTeam',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='jopa',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='phone',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='project_likes',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='requisites',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='role',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='sex',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='skills',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
