# Generated by Django 4.1.2 on 2022-10-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0003_alter_ouruser_bornage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='busyness',
            field=models.CharField(default='15', max_length=200),
        ),
    ]
