# Generated by Django 4.1.2 on 2022-10-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0004_rename_users_testuser_delete_auth_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUser',
        ),
    ]
