# Generated by Django 4.1.2 on 2022-10-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0004_alter_ouruser_busyness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='citizenship',
            field=models.CharField(default='15', max_length=200),
        ),
    ]
