# Generated by Django 4.1.2 on 2022-10-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
