# Generated by Django 4.1.2 on 2022-10-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0008_alter_ouruser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='education',
            field=models.CharField(default='15', max_length=200),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='fio',
            field=models.CharField(default='15', max_length=200),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='image',
            field=models.ImageField(default='15', upload_to=None),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='inn',
            field=models.CharField(default='15', max_length=100),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='isAuthor',
            field=models.CharField(default='15', max_length=100),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='isCompany',
            field=models.CharField(default='15', max_length=100),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='jopa',
            field=models.CharField(default='15', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='phone',
            field=models.CharField(default='15', max_length=30),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='project_likes',
            field=models.CharField(default='15', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='requisites',
            field=models.CharField(default='15', max_length=100),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='role',
            field=models.CharField(default='15', max_length=100),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='skills',
            field=models.CharField(default='15', max_length=1000),
        ),
    ]
